#!/bin/busybox sh
#
# By Chih-Wei Huang <cwhuang@linux.org.tw>
# and Thorsten Glaser <tg@mirbsd.org>
#
# Last updated 2017/10/06
#
# License: GNU Public License
# We explicitely grant the right to use the scripts
# with Android-x86 project.
#

# Forcefully disable install on TWRP ISO
INSTALL=0

if [ ! -z "${RECOVERY_ISOBOOT}" ]; then
	RECOVERY=${RECOVERY_ISOBOOT}
fi

export PATH=/sbin:/bin:/system/bin:/system/xbin;

# configure debugging output
if [ -n "$DEBUG" ]; then
	LOG=/tmp/log
	set -x
else
	LOG=/dev/null
	test -e "$LOG" || busybox mknod $LOG c 1 3
fi
exec 2>> $LOG

# early boot
if test x"$HAS_CTTY" != x"Yes"; then
	# initialise /proc and /sys
	busybox mount -t proc proc /proc
	busybox mount -t sysfs sys /sys
	# let busybox install all applets as symlinks
	busybox --install -s
	# spawn shells on tty 2 and 3 if debug or installer
	if test -n "$DEBUG" || test -n "$INSTALL"; then
		# ensure they can open a controlling tty
		mknod /dev/tty c 5 0
		# create device nodes then spawn on them
		mknod /dev/tty2 c 4 2 && openvt
		mknod /dev/tty3 c 4 3 && openvt
	fi
	if test -z "$DEBUG" || test -n "$INSTALL"; then
		echo 0 0 0 0 > /proc/sys/kernel/printk
	fi
	# initialise /dev (first time)
	mkdir -p /dev/block
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	mdev -s
	# re-run this script with a controlling tty
	exec env HAS_CTTY=Yes setsid cttyhack /bin/sh "$0" "$@"
fi

# now running under a controlling tty; debug output from stderr into log file
# boot up Android

error()
{
	echo $*
	return 1
}

try_mount()
{
	RW=$1; shift
	if [ "${ROOT#*:/}" != "$ROOT" ]; then
		# for NFS roots, use nolock to avoid dependency to portmapper
		RW="nolock,$RW"
	fi
	# FIXME: any way to mount ntfs gracefully?
	mount -o $RW,noatime $@ || mount.ntfs-3g -o rw,force $@
}

check_root()
{
	if [ "`dirname $1`" = "/dev" ]; then
		[ -e $1 ] || return 1
		blk=`basename $1`
		[ ! -e /dev/block/$blk ] && ln $1 /dev/block
		dev=/dev/block/$blk
		blkid $dev | grep -q TYPE || return 1
	else
		dev=$1
	fi

	if [ -z "${RECOVERY_ISOBOOT}" ]; then
		try_mount ro $dev /mnt || return 1
		if [ -n "$iso" -a -e /mnt/$iso ]; then
			mount --move /mnt /iso
			mkdir /mnt/iso
			mount -o loop /iso/$iso /mnt/iso
			SRC=iso
		fi
		if [ -e /mnt/$SRC/$RAMDISK ]; then
			zcat /mnt/$SRC/$RAMDISK | cpio -id > /dev/null
		elif [ -b /dev/$RAMDISK ]; then
			zcat /dev/$RAMDISK | cpio -id > /dev/null
		else
			return 1
		fi
		if [ -e /mnt/$SRC/system.sfs ]; then
			mount -o loop,noatime /mnt/$SRC/system.sfs /sfs
			mount -o loop,noatime /sfs/system.img system
		elif [ -e /mnt/$SRC/system.img ]; then
			remount_rw
			mount -o loop,noatime /mnt/$SRC/system.img system
		elif [ -d /mnt/$SRC/system ]; then
			remount_rw
			mount --bind /mnt/$SRC/system system
		elif [ -e /mnt/build.prop ]; then
			mount --bind /mnt system
		else
			rm -rf *
			return 1
		fi
	else
		if [ -z "${RAMDISK_LOCATED}" ]; then
			try_mount ro $dev /mnt || return 1
			if [ -e /mnt/$SRC/$RAMDISK ]; then
				zcat /mnt/$SRC/$RAMDISK | cpio -id > /dev/null
				mount --move /mnt /iso
				RAMDISK_LOCATED=1
			fi

			# We always return 1 even if we got the ramdisk, because we want the RW.
			# If it is the correct disk (such as hdd install), it will come back around.
			# This could be improved.
			return 1;
		else
			# TODO: Write a selection menu if more than one suspected install is found.
			# Until then, only use first matching result.

			try_mount rw $dev /mnt || return 1
			if [ $(ls -1 /mnt/*/system.img | head -n1 | wc -l) -ne 0 ]; then
				mount -o loop,noatime $(ls -1 /mnt/*/system.sfs | head -n1) /sfs
				mount -o loop,noatime /sfs/system.img system
        	        elif [ $(ls -1 /mnt/*/system.img | head -n1 | wc -l) -ne 0 ]; then
	                        mount -o loop,noatime $(ls -1 /mnt/*/system.img | head -n1) system
	                elif [ $(ls -1d /mnt/*/system | head -n1 | wc -l) -ne 0 ]; then
	                        mount --bind $(ls -1d /mnt/*/system | head -n1) system
	                elif [ -e /mnt/build.prop ]; then
	                        mount --bind /mnt system
        	        else
	                        return 1
	                fi
		fi
	fi
	mkdir -p mnt
	echo " found at $1"
	rm /sbin/mke2fs
	hash -r
}

remount_rw()
{
	# "foo" as mount source is given to workaround a Busybox bug with NFS
	# - as it's ignored anyways it shouldn't harm for other filesystems.
	mount -o remount,rw foo /mnt
}

debug_shell()
{
	if [ -x /system/bin/sh ]; then
		echo Running MirBSD Korn Shell...
		USER="($1)" system/bin/sh -l 2>&1
	else
		echo Running busybox ash...
		sh 2>&1
	fi
}

if [ ! -z "${RECOVERY}" ]; then
	echo -n Detecting writable Android-x86 for recovery...
else
	echo -n Detecting Android-x86...
fi

[ -z "$SRC" -a -n "$BOOT_IMAGE" ] && SRC=`dirname $BOOT_IMAGE`
if [ ! -z "${RECOVERY}" ]; then
	[ -z "$RAMDISK" ] && RAMDISK=ramdisk-recovery.img || RAMDISK=${RAMDISK##/dev/}
else
	[ -z "$RAMDISK" ] && RAMDISK=ramdisk.img || RAMDISK=${RAMDISK##/dev/}
fi

for c in `cat /proc/cmdline`; do
	case $c in
		iso-scan/filename=*)
			eval `echo $c | cut -b1-3,18-`
			;;
		*)
			;;
	esac
done

mount -t tmpfs tmpfs /android
cd /android
while :; do
	for device in ${ROOT:-/dev/[hmnsv][dmrv][0-9a-z]*}; do
		check_root $device && break 2
		mountpoint -q /mnt && umount /mnt
	done
	sleep 1
	echo -n .
done

ln -s mnt/$SRC /src

if [ ! -z "${RECOVERY}" ]; then
	mkdir /android/src
	mount -o bind /src /android/src
fi

ln -s android/system /

if [ ! -z "${RECOVERY}" ]; then
	# Ramdisk (uses independant modules)
	ln -s /android/lib/firmware /android/lib/modules /lib
else
	# System (uses standard method)
	ln -s ../system/lib/firmware ../system/lib/modules /lib
fi

if [ -n "$INSTALL" ]; then
	zcat /src/install.img | ( cd /; cpio -iud > /dev/null )
fi

if [ -x system/bin/ln -a \( -n "$DEBUG" -o -n "$BUSYBOX" \) ]; then
	mv /bin /lib .
	sed -i 's|\( PATH.*\)|\1:/bin|' init.environ.rc
	rm /sbin/modprobe
	busybox mv /sbin/* sbin
	rmdir /sbin
	ln -s android/bin android/lib android/sbin /
	hash -r
fi

if [ ! -z "${UVESAFB}" ]; then
	if [ "${UVESAFB}" == "1" ]; then
		modprobe uvesafb mtrr=3 scroll=redraw mode_option=1024x768-16 v86d=/android/sbin/v86d
	else
		modprobe uvesafb mtrr=3 scroll=redraw mode_option=${UVESAFB} v86d=/android/sbin/v86d
	fi
fi

# load scripts
for s in `ls /scripts/* /src/scripts/*`; do
	test -e "$s" && source $s
done

# ensure keyboard driver is loaded
[ -n "$INSTALL" -o -n "$DEBUG" ] && auto_detect &

if [ 0$DEBUG -gt 0 ]; then
	echo -e "\nType 'exit' to continue booting...\n"
	debug_shell debug-found
fi

# A target should provide its detect_hardware function.
# On success, return 0 with the following values set.
# return 1 if it wants to use auto_detect
[ "$AUTO" != "1" ] && detect_hardware && FOUND=1

[ -n "$INSTALL" ] && do_install

load_modules
mount_data
mount_sdcard
setup_tslib
setup_dpi
post_detect
# Give devices time to appear...

echo -n "Waiting for devices to settle"
for f in $(seq 1 6); do
	echo -n "."
	sleep 1;
done
echo -e "\n";

# If we need nwfermi, load it before switching
# Because we cannot load it once in Android
# due to it being a dynamically linked closed source binary

if [ $(cat /sys/bus/*/devices/*/uevent | grep "PRODUCT=1926" | wc -l) -gt 0 ]; then
	# There is a NextWindow device, so load and wait for nwfermi
	# Although this is probably not the best way...
	echo -n "Detected NextWindow TS: Loading support..."
	/bin/busybox modprobe nw-fermi
	while [ $(ls -l /dev/nwfermi* | wc -l) -eq 0 ]; do
		sleep 1
		echo -n "."
	done
	echo -e " done.\n"
	/sbin/nwfermi_daemon /daemon
fi

if [ 0$DEBUG -gt 1 ]; then
	echo -e "\nUse Alt-F1/F2/F3 to switch between virtual consoles"
	echo -e "Type 'exit' to enter Android...\n"

	debug_shell debug-late
	SETUPWIZARD=${SETUPWIZARD:-0}
fi

[ "$SETUPWIZARD" = "0" ] && echo "ro.setupwizard.mode=DISABLED" >> default.prop

[ -n "$DEBUG" ] && SWITCH=${SWITCH:-chroot}

# We must disable mdev before switching to Android
# since it conflicts with Android's init
echo > /proc/sys/kernel/hotplug

export ANDROID_ROOT=/system

if [ ! -z "${UVESAFB}" ]; then
	printf '\033[?12l' > /dev/tty1
	echo 0 > /sys/class/graphics/fbcon/cursor_blink
fi

exec ${SWITCH:-switch_root} /android /init

# avoid kernel panic
while :; do
	echo
	echo '	Android-x86 console shell. Use only in emergencies.'
	echo
	debug_shell fatal-err
done
